### ISSUE TITLE
优惠券图片无法发送到群聊

### ISSUE THREAD

**Issue by why2lyj** [why2lyj/youxiang#1]
发送优惠券信息时，图片确实：
具体错误提示：
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
>     raise err
>   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
>     sock.connect(sa)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
>     chunked=chunked,
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
>     conn = self._new_conn()
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 167, in _new_conn
>     % (self.host, self.timeout),
> urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa3513b1d50>, 'Connection to wx.qq.com timed out. (connect timeout=10)')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=TWr/6Hm3rfEZLeAG&skey=@crypt_1ff95946_6d5499d21fb1059cb79d2119e1b96d69&pass_ticket=WU8gouerkJ7MdUCvYBlTWKtx574TZUKB0QFAl01tko2b1wYG89dThD%2BXQWag3NjS (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa3513b1d50>, 'Connection to wx.qq.com timed out. (connect timeout=10)'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 253, in maintain_loop
>     msgList, contactList = self.get_msg()
>   File "/usr/local/lib/python3.7/site-packages/itchat/components/login.py", line 334, in get_msg
>     r = self.s.post(url, data=json.dumps(data), headers=headers, timeout=config.TIMEOUT)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 578, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
>     raise ConnectTimeout(e, request=request)
> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='wx.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/webwxsync?sid=TWr/6Hm3rfEZLeAG&skey=@crypt_1ff95946_6d5499d21fb1059cb79d2119e1b96d69&pass_ticket=WU8gouerkJ7MdUCvYBlTWKtx574TZUKB0QFAl01tko2b1wYG89dThD%2BXQWag3NjS (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa3513b1d50>, 'Connection to wx.qq.com timed out. (connect timeout=10)'))
>

**Comment by why2lyj** [comment]
此问题不修复。
