### ISSUE TITLE
安装错误，求解

### ISSUE THREAD

**Issue by ghost** [why2lyj/youxiang#22]
Traceback (most recent call last):
  File "/youxiang/main.py", line 6, in <module>
    from chat.wechat import *
  File "/youxiang/chat/wechat.py", line 23, in <module>
    from chat.message import handle_friends_message, handle_groups_message, handle_group_pictures
  File "/youxiang/chat/message.py", line 11, in <module>
    from untils.ad import QRcode_detection
  File "/youxiang/untils/ad.py", line 5, in <module>
    import pyzbar.pyzbar as pyzbar
  File "/usr/local/lib/python3.7/site-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/usr/local/lib/python3.7/site-packages/pyzbar/wrapper.py", line 143, in <module>
    c_uint_p,    # minor
  File "/usr/local/lib/python3.7/site-packages/pyzbar/wrapper.py", line 136, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/usr/local/lib/python3.7/site-packages/pyzbar/wrapper.py", line 115, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/usr/local/lib/python3.7/site-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library

**Comment by why2lyj** [comment]
如提示所说 ```Unable to find zbar shared library```
